# Generated by Django 4.0.4 on 2022-07-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='image',
            field=models.TextField(),
        ),
    ]
