# Generated by Django 4.0.4 on 2022-07-18 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_headline_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headline',
            old_name='image',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='headline',
            old_name='url',
            new_name='location',
        ),
    ]
