# Generated by Django 4.0.4 on 2022-07-19 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_image_headline_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headline',
            old_name='company',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='headline',
            old_name='location',
            new_name='snippet',
        ),
    ]
